### ISSUE TITLE
kpie crashes if an app pops up a short-lived dialog

### ISSUE THREAD

**Issue by richtrefz** [skx/kpie#19] opened 2018-02-12 20:32 UTC
As title says, the problem appears to be a dlalog that appears and then disappears so quickly that the API calls aren't being used on a valid window.  I think its window_application that has the most trouble.
I tried wrapping my function in xpcall, but it didn't help this case. 

This is what I see in console.

`The program 'kpie' received an X Window System error.`
`This probably reflects a bug in the program.`
`The error was 'BadWindow (invalid Window parameter)'.`
`  (Details: serial 26483 error_code 3 request_code 20 minor_code 0)`

Any ideas appreciated.

**Comment by skx** [comment] 2018-02-14 04:03
Hrm that's a tricky one.  I think I can picture the situation you're describing:

* Window opens.
* Kpie gets invoked.
  * By the time Lua functions are executed the window has already gone away.
     * Which triggers a crash.

I think  the only sane thing to do is to go through the code, and ensure that we add decent error-handling.  For the case of `window_application` the current code is:

        WnckApplication *a = wnck_window_get_application(g_window);
        lua_pushstring(L, wnck_application_get_name(a));
       return 1;

I guess that needs to be something like:

        WnckApplication *a = wnck_window_get_application(g_window);
        char *name =  wnck_application_get_name(a);
        if ( name != NULL )
             lua_pushstring(L,name);
        else 
             lua_pushnil(L);
       return 1;

That shouldn't be _too hard_, but it will be a bit time-consuming.   The only alternative would be to add some call to a "is window valid?" primitive to each Lua primitive, but looking at the documentation I don't see an obvious candidate:

* https://developer.gnome.org/libwnck/stable/

**Comment by richtrefz** [comment] 2018-02-14 14:01
Thank you for responding.  You verified for me that there is no easy obvious solution.  I don't know why xpcall didn't seem to help.

When this started happening, I put these at the top of my script

`title = window_title()`
`print ("title " .. title)`
`class = window_class()`
`print ("class " .. class)`
`role  = window_role()`
`print ("role " .. role)`
`app   = window_application()`
`print ("app " .. app)`
`type  = window_type()`
`print ("type " .. type)`

The title and class seemed to get printed and the others not always.  I don't know if that was due to timing or other.

My "solution" for right now is to check if the title is one that causes the crash, and simply `return`.

When I get a few minutes, I'll try your window_application suggestion and see what happens.

Thanks again

**Comment by skx** [comment] 2018-02-14 14:04
I tried to reproduce the problem by adding `sleep` calls in the bindings.c function - with the intention  I could open a window, and then close it quickly.  But the results I received weren't useful.

(I didn't see any crashes, or errors.)

**Comment by richtrefz** [comment] 2018-02-14 14:35
It looks like its window_role that is actually the problem.  I moved the get/print of role to last and the other 4 prints are OK.

So it would fail more consistently, I put this in my LUA script

```
function sleep(s)
  local ntime = os.clock() + s
  repeat until os.clock() > ntime
end
sleep(0.1)
```

```
-- dumpinfo 
--  window_xid 123733035
title Processing Message
class Thunderbird
app Thunderbird
type WINDOW_DIALOG
The program 'kpie' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 1741 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```

**Comment by skx** [comment] 2018-02-14 15:52
> It looks like its window_role that is actually the problem. 

Thank-you.  That was the hint I needed, I can now reproduce the problem and will submit a fix tonight/tomorrow.

**Comment by skx** [comment] 2018-02-14 16:23
I hope the commit I've just pushed fixes things for you - if you can confirm I'll make a new (binary) release over the next few days.

**Comment by richtrefz** [comment] 2018-02-14 17:16
This bug is difficult to get rid of 
```
-- dumpinfo 
--  window_xid 123733766
title Check Spelling
class Thunderbird
app Thunderbird
type WINDOW_DIALOG
The program 'kpie' received an X Window System error.
```
I see the new
`    XSetErrorHandler( x11_error_catcher );`
but it didn't seem to change anything.

**Comment by skx** [comment] 2018-02-14 17:25
I've tested moving it here - and it seems to not-crash for me.

* https://github.com/skx/kpie/commit/764acb16c14d224c4ea57a1d2b2821ba01a86ba9

One more try?

**Comment by richtrefz** [comment] 2018-02-14 17:25
It is very affected by timing - apparently 2 dlg's get created quickly

it gets by this one
```
-- dumpinfo 
--  window_xid 123733848
title Check Spelling
class Thunderbird
app Thunderbird
type WINDOW_DIALOG
role 
```
then fails on the next one
```
-- dumpinfo 
--  window_xid 123733863
title Processing Message
class Thunderbird
app Thunderbird
type WINDOW_DIALOG
The program 'kpie' received an X Window System error.
```
So my little sleep function in LUA really helps to expose it.  Without the 0.1s sleep it wasn't happening for me much - today.  Whether it fails or not probably depends on how loaded the system is and how quickly kpie runs.

**Comment by skx** [comment] 2018-02-14 17:26
(Yes - I'd been adding "sleep(5)" to `invoke_lua()` to make it more repeatable)

**Comment by richtrefz** [comment] 2018-02-14 17:27
I just saw your "put", I will try in shortly

**Comment by richtrefz** [comment] 2018-02-14 17:34
Looks Good !!!

```
-- dumpinfo 
--  window_xid 123734183
title Check Spelling
class Thunderbird
app Thunderbird
type WINDOW_DIALOG
An error was caught!
role 

-- dumpinfo 
--  window_xid 123734198
title Processing Message
class Thunderbird
app Thunderbird
type WINDOW_DIALOG
An error was caught!
role 

```

Thank you !!!

**Comment by skx** [comment] 2018-02-14 17:52
Great.  I'm a little unsure why installing it just the once, rather than around each call, didn't work.  But I should have tested more carefully.

Thank __you__ for the bug report, its only when I see things like this that I get the chance to make improvements.

I'll make a release in the next day or two, (probably undoing the work in #14 since that was never confirmed as working and it's a pain to manage), with this in and a new version/changelog entry.

**Comment by richtrefz** [comment] 2018-02-14 17:59
Would it make sense to set Role to "X-ERROR-OCCURRED" or something?  Or is there a way for me to test that Role failed.  I'd rather just skip the remainder of script in that case - and not keep making API calls to a non-existent window.

**Comment by skx** [comment] 2018-02-14 18:03
Right now if that fails it returns an empty-string.  I think that's probably a reasonable default, because the only real alternative to keep things clean would be to return `nil` - and that can cause errors if your Lua script(s) aren't expecting it.

I guess if you want to skip you could do that via "len(role) < 1", or similar.

**Comment by richtrefz** [comment] 2018-02-14 18:17
It seems numerous windows normally have an empty string for a role so string.len() is zero in both cases.

**Comment by skx** [comment] 2018-02-14 18:20
I guess I'd be happy to return either:

* The value, if set.
* "" if nothing.
* nil in the case of error

But I think creating a fake-error-string would be a bit wrong.  Could you live with that?

**Comment by richtrefz** [comment] 2018-02-14 18:22
That would be perfect.   Thank you !

**Comment by skx** [comment] 2018-02-14 18:24
No problem.

I'll sort it out tomorrow, or before the weekend at least.

**Comment by skx** [comment] 2018-02-15 17:40
Fixed now - the function will return a string (which might be empty) or `nil` on error.

**Closed by skx** 2018-02-15 17:40 UTC

**Comment by skx** [comment] 2018-02-15 18:03
New binary releases made for Debian - including stretch.
